pages/admin/list:
  path: /pages/admin/list
  controller: ['App\Module\Pages\Controller\Admin', 'list']
  options:
    aclComment: "[Pages][Admin] Список всех страниц (обзор)"

pages/admin/addpage:
  path: /pages/admin/addpage
  controller: ['App\Module\Pages\Controller\Admin', 'add']
  options:
    aclComment: "[Pages][Admin] Добавить новую страницу"








